/* STUDENTS:  DO NOT EDIT THIS FILE.  INSTEAD, MODIFY YOUR OWN PROJECT
 * CODE TO FIT THE SPECIFICATION GIVEN BY THE TESTS IN THIS FILE.
 *
 * If you DO modify it, we overwrite it with a fresh version from our repo
 * when grading, so you can't use it to fudge the tests anyway.
 *
 * This file is used by the CS3081W auto-grading system.
 *
 * Please note, the assessment tests for grading, will use the same include
 * files, class names, and function names for accessing students' code that you
 * find in this file.  So students, if you write your code so that it passes
 * these feedback tests, you can be assured that the auto-grader will at least
 * be able to properly link with your code.
 */

/*******************************************************************************
 * Includes
 ******************************************************************************/
#include <gtest/gtest.h>

#include <iostream>
#include <string>
#include <list>
#include <string>

#include "../src/passenger_loader.h"
#include "../src/passenger_unloader.h"
#include "../src/passenger.h"
#include "../src/stop.h"

using namespace std;

/******************************************************
* TEST FEATURE SetUp
*******************************************************/
class PassengerTests : public ::testing::Test {
protected:
  PassengerLoader* pass_loader;
  PassengerUnloader* pass_unloader;
  Passenger *passenger, *passenger1, *passenger2;
    
  virtual void SetUp() {
    pass_loader = new PassengerLoader();
    pass_unloader = new PassengerUnloader();
  }

  virtual void TearDown() {
    delete pass_loader;
    delete pass_unloader;
    delete passenger;
    passenger = NULL;
    pass_loader = NULL;
    pass_unloader = NULL;
  }
};


/*******************************************************************************
 * Test Cases
 ******************************************************************************/
TEST_F(PassengerTests, Constructor) {
  passenger = new Passenger();
  EXPECT_EQ(passenger->IsOnBus(), false);
  passenger->GetOnBus();
  EXPECT_EQ(passenger->IsOnBus(), true);
};


TEST_F(PassengerTests, Tests) {
  list<Passenger*> passengers;
  EXPECT_EQ(passengers.size(), 0);

  // Make a passenger
  Stop* stop = new Stop(123);
  int destination_stop_id = stop->GetId();
  string passenger_name = "P1";
  passenger = new Passenger(destination_stop_id, passenger_name);

  // Load the passenger 
  int passengers_loaded = pass_loader->LoadPassenger(passenger, 10, &passengers);
  EXPECT_EQ(passengers_loaded, 1);
  EXPECT_EQ(passengers.size(), 1);

  // check if passenger 'p1' is on Bus
  EXPECT_TRUE(passenger->IsOnBus());

  // Now unload the same passenger  
  int passengers_unloaded = pass_unloader->UnloadPassengers(passengers, stop);
  EXPECT_EQ(passengers_unloaded, 1);
  EXPECT_EQ(passengers.size(), 0);
    
  delete stop;
};

TEST_F(PassengerTests, TimeInit) {
  passenger = new Passenger();
  EXPECT_EQ(passenger->GetTotalWait(), 0);
};

TEST_F(PassengerTests, IdInit) {
  passenger1 = new Passenger(12,"John Doe");
  EXPECT_EQ(passenger1->GetDestination(), 12);
  passenger2 = new Passenger(16,"Apple Bee");
  EXPECT_EQ(passenger2->GetDestination(), 16);
};
